Add Flatpak global overrides file
endlessm/clippy pull request #6
Opened 2018-09-19 09:43 UTC by joaquimrocha

This file will be linked from the actual Flatpak global overrides file,
so we can easily update those overridden options.

Currently, it is used to ensure that all apps are launched with access
to the Clippy module and with the GTK3 module env var pointing to it.

https://phabricator.endlessm.com/T23834

2018-09-19 09:51 UTC, ramcq requested changes
There is nothing about this file which means it can only be used as a global override, I think it should be named flatpak-override or so - whoever makes the symlink can decide if they are overriding global, one app, etc.

I thought we also discussed adding a -split version which would be the same, but embed the /var/endless-extra path for split images?

Finally: I would put this in a data dir (ie /app/share/...), not etc. It doesn't make much sense to have etc inside a Flatpak app to me - it's not editable. :)

2018-09-19 10:07 UTC, joaquimrocha commented
@ramcq That makes sense.
I had actually used an `/app/share/flatpak` dir in the beginning, but that seemed completely arbitrary, so the `etc` looked better IMO, even if it's not writable.

2018-09-19 10:09 UTC, joaquimrocha commented
As for the split version, I thought we had agreed it'd be something for later as we don't have Code split images, right?

2018-09-19 10:27 UTC, joaquimrocha commented
PR updated.

2018-09-20 15:50 UTC, ramcq commented
Missing `git add`?

2018-09-20 15:50 UTC, ramcq requested changes
flatpak-overrides file is missing?

2018-09-20 16:16 UTC, joaquimrocha commented
Oops! Thanks @ramcq . I've updated the branch.

2018-09-20 16:19 UTC, ramcq approved these changes

2018-09-20 16:21 UTC, merged

2018-09-20 16:23 UTC, joaquimrocha commented
Merged after @ramcq approval.